In [1]:
import numpy as np
print(f"NumPy Version: {np.__version__}")
# If this works without an error, your 'engine' is officially warmed up.

NumPy Version: 2.4.2


In [2]:
import numpy as np

I = np.eye(5)
print(I)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [3]:
diag = np.diag(I)
print(diag)


[1. 1. 1. 1. 1.]


In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

manual = sum(x*y for x, y in zip(a, b))
print("Manual:", manual)


Manual: 32


In [5]:
print("np.dot:", np.dot(a, b))


np.dot: 32


data = np.genfromtxt("diabetes.csv", delimiter=",", skip_header=1)

means = np.mean(data, axis=0)
stds = np.std(data, axis=0)
mins = np.min(data, axis=0)
maxs = np.max(data, axis=0)

print("Means:", means)
print("Stds:", stds)
print("Mins:", mins)
print("Maxs:", maxs)


In [8]:
import numpy as np

# Load clinic_day.csv as pure numeric data (skip the PatientID column)
data = np.genfromtxt(
    "clinic_day.csv",
    delimiter=",",
    skip_header=1,
    usecols=(1, 2, 3)  # Glucose, HeartRate, OxygenSat
)

print("Data shape:", data.shape)  # should be (4, 3)

means = np.mean(data, axis=0)
stds = np.std(data, axis=0)
mins = np.min(data, axis=0)
maxs = np.max(data, axis=0)

print("Means (Glucose, HR, O2):", means)
print("Stds  (Glucose, HR, O2):", stds)
print("Mins  (Glucose, HR, O2):", mins)
print("Maxs  (Glucose, HR, O2):", maxs)


Data shape: (4, 3)
Means (Glucose, HR, O2): [132.5   86.75  95.  ]
Stds  (Glucose, HR, O2): [24.1091269  10.08402202  2.23606798]
Mins  (Glucose, HR, O2): [95. 72. 92.]
Maxs  (Glucose, HR, O2): [160. 100.  98.]


### NumPy stats on clinic_day.csv

Compute `np.mean`, `np.std`, `np.min`, `np.max` for Glucose, HeartRate, and OxygenSat using `np.genfromtxt`.


In [9]:
x = data[:, 0]
x_norm = (x - x.min()) / (x.max() - x.min())
print(x_norm)


[0.         0.76923077 0.53846154 1.        ]


In [10]:
theta = np.radians(45)
R = np.array([
    [np.cos(theta), -np.sin(theta)],
    [np.sin(theta),  np.cos(theta)]
])
v = np.array([1, 0])
rotated = R @ v
print(rotated)  # ~ [0.707, 0.707]


[0.70710678 0.70710678]


In [11]:
# 1. Rotate 90 degrees — should give [0, 1] (pointing straight up)
theta90 = np.radians(90)
R90 = np.array([[np.cos(theta90), -np.sin(theta90)],
                [np.sin(theta90),  np.cos(theta90)]])
print(R90 @ np.array([1, 0]))

# 2. Rotate twice — should be same as rotating 90 degrees once
print(R90 @ (R90 @ np.array([1, 0])))   # 180 degrees total -> [-1, 0]

# 3. What is the determinant of any rotation matrix?
print(np.linalg.det(R90))   # always 1.0

[6.123234e-17 1.000000e+00]
[-1.0000000e+00  1.2246468e-16]
1.0


In [12]:
M = np.arange(9).reshape(3, 3)
print(M)
print("Diagonal:", np.diag(M))
# np.diag works on any 2D array. For a square matrix

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Diagonal: [0 4 8]


In [13]:
M2 = np.arange(12).reshape(3, 4)
print(M2)
print("Diagonal:", np.diag(M2))
# For a non-square matrix, NumPy just takes the diagonal up to the shortest dimension

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Diagonal: [ 0  5 10]


In [15]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("Matrix product:\n", np.dot(A, B))
# or more idiomatic:
print("Matrix product:\n", A @ B)
# Dot products generalise to matrix multiplication
#  @ is the cleanest operator for matrix multiplication.

Matrix product:
 [[19 22]
 [43 50]]
Matrix product:
 [[19 22]
 [43 50]]


In [16]:
columns = ["Glucose", "HeartRate", "OxygenSat"]

means = np.mean(data, axis=0)
stds = np.std(data, axis=0)
mins = np.min(data, axis=0)
maxs = np.max(data, axis=0)

for col, mean, std, min_, max_ in zip(columns, means, stds, mins, maxs):
    print(f"{col:10} | mean={mean:.2f}, std={std:.2f}, min={min_}, max={max_}")
# Instead of raw arrays, you can pair results with column names

Glucose    | mean=132.50, std=24.11, min=95.0, max=160.0
HeartRate  | mean=86.75, std=10.08, min=72.0, max=100.0
OxygenSat  | mean=95.00, std=2.24, min=92.0, max=98.0


In [17]:
normed = (data - data.min(axis=0)) / (data.max(axis=0) - data.min(axis=0))
print(normed)
# Instead of normalising one column, you can normalise all at once

[[0.         0.         1.        ]
 [0.76923077 0.64285714 0.33333333]
 [0.53846154 0.46428571 0.66666667]
 [1.         1.         0.        ]]


In [18]:
print("Column mins after norm:", normed.min(axis=0))
print("Column maxs after norm:", normed.max(axis=0))


Column mins after norm: [0. 0. 0.]
Column maxs after norm: [1. 1. 1.]
